// Generated by CIRCT firtool-1.62.1
// external module MemDPIC

// external module RegfileDPIC

// VCS coverage exclude_file
module reg_32x32(	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  input  [4:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [31:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
  input         R1_clk,
  output [31:0] R1_data,
  input  [4:0]  R2_addr,
  input         R2_en,
  input         R2_clk,
  output [31:0] R2_data,
  input  [4:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:31];	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  always @(posedge W0_clk) begin	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
    if (W0_en & 1'h1)	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
      Memory[W0_addr] <= W0_data;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  assign R2_data = R2_en ? Memory[R2_addr] : 32'bx;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
endmodule

module Regfiles(	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7
  input         clock,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7
  input  [4:0]  io_raddr1,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  output [31:0] io_rdata1,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  input  [4:0]  io_raddr2,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  output [31:0] io_rdata2,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  input  [4:0]  io_waddr,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  input  [31:0] io_wdata,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  input         io_wen,	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
  output [31:0] io_a0_val	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:6:16
);

  wire [31:0] _reg_ext_R0_data;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  wire [31:0] _reg_ext_R1_data;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
  reg_32x32 reg_ext (	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:20:18
    .R0_addr (io_raddr2),
    .R0_en   (1'h1),	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7
    .R0_clk  (clock),
    .R0_data (_reg_ext_R0_data),
    .R1_addr (io_raddr1),
    .R1_en   (1'h1),	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7
    .R1_clk  (clock),
    .R1_data (_reg_ext_R1_data),
    .R2_addr (5'hA),	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:29:21
    .R2_en   (1'h1),	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7
    .R2_clk  (clock),
    .R2_data (io_a0_val),
    .W0_addr (io_waddr),
    .W0_en   (io_wen & (|io_waddr)),	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:25:{17,29}
    .W0_clk  (clock),
    .W0_data (io_wdata)
  );
  RegfileDPIC regfile_dpic (	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:31:30
    .clk   (clock),
    .wen   (io_wen),
    .waddr (io_waddr),
    .wdata (io_wdata)
  );
  assign io_rdata1 = io_raddr1 == 5'h0 ? 32'h0 : _reg_ext_R1_data;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7, :20:18, :22:{21,31}
  assign io_rdata2 = io_raddr2 == 5'h0 ? 32'h0 : _reg_ext_R0_data;	// home/marigold/kanna/rv32i/npc/playground/src/utils/Regfiles.scala:5:7, :20:18, :22:{21,31}, :23:{21,31}
endmodule

module ALU(	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:6:7
  input  [4:0]  io_alu_op,	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:7:16
  input  [31:0] io_alu_src1,	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:7:16
  input  [31:0] io_alu_src2,	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:7:16
  output [31:0] io_alu_res	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:7:16
);

  wire [31:0] _GEN = {27'h0, io_alu_src2[4:0]};	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:14:28, :22:40
  wire [62:0] sll_res = {31'h0, io_alu_src1} << io_alu_src2[4:0];	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:14:28, :24:33
  assign io_alu_res =
    io_alu_op == 5'hA
      ? io_alu_src1 >> _GEN
      : io_alu_op == 5'h9
          ? sll_res[31:0]
          : io_alu_op == 5'h7
              ? $signed($signed(io_alu_src1) >>> _GEN)
              : io_alu_op == 5'h6
                  ? 32'(io_alu_src1 - io_alu_src2)
                  : io_alu_op == 5'h8
                      ? io_alu_src1 & io_alu_src2
                      : io_alu_op == 5'h5
                          ? io_alu_src1 | io_alu_src2
                          : io_alu_op == 5'h4
                              ? io_alu_src1 ^ io_alu_src2
                              : io_alu_op == 5'h2
                                  ? {31'h0, io_alu_src1 < io_alu_src2}
                                  : io_alu_op == 5'h3
                                      ? {31'h0,
                                         $signed(io_alu_src1) < $signed(io_alu_src2)}
                                      : io_alu_op == 5'h1
                                          ? 32'(io_alu_src1 + io_alu_src2)
                                          : 32'h0;	// home/marigold/kanna/rv32i/npc/playground/src/utils/ALU.scala:6:7, :16:32, :17:40, :18:33, :19:33, :20:33, :21:33, :22:40, :23:33, :24:33, :25:33, :26:49
endmodule

// external module EbreakDPIC

// external module ITraceDPIC

module NPC_Top(	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7
  input         clock,	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7
  input         reset,	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7
  output [31:0] io_pc,	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:15:16
  output        io_is_mmio	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:15:16
);

  wire [31:0]      _dmem_rdata;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:121:22
  wire [31:0]      _alu_io_alu_res;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21
  wire [31:0]      _regfile_io_rdata1;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25
  wire [31:0]      _regfile_io_rdata2;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25
  wire [31:0]      _regfile_io_a0_val;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25
  wire [31:0]      _imem_rdata;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22
  reg  [31:0]      pc;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21
  wire [9:0]       _GEN = {_imem_rdata[14:12], _imem_rdata[6:0]};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_1 = _GEN == 10'h13;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_3 = _GEN == 10'h67;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_5 = _imem_rdata == 32'h100073;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [16:0]      _GEN_0 = {_imem_rdata[31:25], _imem_rdata[14:12], _imem_rdata[6:0]};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_7 = _GEN_0 == 17'h33;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_9 = _imem_rdata[6:0] == 7'h37;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_11 = _GEN == 10'h103;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_13 = _GEN == 10'h203;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_15 = _GEN == 10'h123;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_17 = _GEN == 10'h23;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_19 = _imem_rdata[6:0] == 7'h17;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_21 = _imem_rdata[6:0] == 7'h6F;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_23 = _GEN == 10'h193;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_25 = _GEN == 10'h113;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_27 = _GEN == 10'hE3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_29 = _GEN_0 == 17'h233;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_31 = _GEN == 10'h213;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_33 = _GEN_0 == 17'h1B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_35 = _GEN_0 == 17'h333;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_37 = _GEN == 10'h313;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_39 = _GEN_0 == 17'h8033;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [15:0]      _GEN_1 = {_imem_rdata[31:26], _imem_rdata[14:12], _imem_rdata[6:0]};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_41 = _GEN_1 == 16'h4293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_43 = _GEN_0 == 17'h82B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_45 = _GEN == 10'hA3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_47 = _GEN_0 == 17'h3B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_49 = _GEN == 10'h393;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_51 = _GEN_0 == 17'hB3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_53 = _GEN_1 == 16'h93;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_55 = _GEN == 10'h2E3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_57 = _GEN == 10'h63;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_59 = _GEN_1 == 16'h293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_61 = _GEN_0 == 17'h2B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_63 = _GEN == 10'h3E3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_65 = _GEN == 10'h363;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_67 = _GEN_0 == 17'h133;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_69 = _GEN == 10'h263;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_71 = _GEN == 10'h83;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_73 = _GEN == 10'h283;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _signals_T_75 = _GEN == 10'h3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _GEN_2 = _signals_T_71 | _signals_T_73 | _signals_T_75;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_3 = _signals_T_63 | _signals_T_65;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_4 = _signals_T_59 | _signals_T_61;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_5 = _signals_T_55 | _signals_T_57;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_6 = _signals_T_51 | _signals_T_53;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_7 = _signals_T_41 | _signals_T_43;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_8 = _signals_T_1 | _signals_T_3;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_9 = _signals_T_15 | _signals_T_17;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [1:0]       signals_1 =
    _GEN_8
      ? 2'h1
      : _signals_T_5
          ? 2'h0
          : _signals_T_7
              ? 2'h1
              : _signals_T_9
                  ? 2'h0
                  : _signals_T_11 | _signals_T_13 | _GEN_9
                      ? 2'h1
                      : _signals_T_19
                          ? 2'h2
                          : _signals_T_21
                              ? 2'h0
                              : {1'h0,
                                 _signals_T_23 | _signals_T_25 | _signals_T_27
                                   | _signals_T_29 | _signals_T_31 | _signals_T_33
                                   | _signals_T_35 | _signals_T_37 | _signals_T_39
                                   | _signals_T_41 | _signals_T_43 | _signals_T_45
                                   | _signals_T_47 | _signals_T_49 | _signals_T_51
                                   | _signals_T_53 | _signals_T_55 | _signals_T_57
                                   | _signals_T_59 | _signals_T_61 | _signals_T_63
                                   | _signals_T_65 | _signals_T_67 | _signals_T_69
                                   | _GEN_2};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:30:19, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_10 = _signals_T_23 | _signals_T_25;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_11 = _signals_T_11 | _signals_T_13;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [2:0]       signals_2 =
    _GEN_8
      ? 3'h2
      : _signals_T_5
          ? 3'h0
          : _signals_T_7
              ? 3'h1
              : _signals_T_9
                  ? 3'h5
                  : _GEN_11
                      ? 3'h2
                      : _GEN_9
                          ? 3'h3
                          : _signals_T_19
                              ? 3'h5
                              : _signals_T_21
                                  ? 3'h4
                                  : _GEN_10
                                      ? 3'h2
                                      : _signals_T_27
                                          ? 3'h6
                                          : _signals_T_29
                                              ? 3'h1
                                              : _signals_T_31
                                                  ? 3'h2
                                                  : _signals_T_33 | _signals_T_35
                                                      ? 3'h1
                                                      : _signals_T_37
                                                          ? 3'h2
                                                          : _signals_T_39
                                                              ? 3'h1
                                                              : _signals_T_41
                                                                  ? 3'h2
                                                                  : _signals_T_43
                                                                      ? 3'h1
                                                                      : _signals_T_45
                                                                          ? 3'h3
                                                                          : _signals_T_47
                                                                              ? 3'h1
                                                                              : _signals_T_49
                                                                                  ? 3'h2
                                                                                  : _signals_T_51
                                                                                      ? 3'h1
                                                                                      : _signals_T_53
                                                                                          ? 3'h2
                                                                                          : _GEN_5
                                                                                              ? 3'h6
                                                                                              : _signals_T_59
                                                                                                  ? 3'h2
                                                                                                  : _signals_T_61
                                                                                                      ? 3'h1
                                                                                                      : _GEN_3
                                                                                                          ? 3'h6
                                                                                                          : _signals_T_67
                                                                                                              ? 3'h1
                                                                                                              : _signals_T_69
                                                                                                                  ? 3'h6
                                                                                                                  : {1'h0,
                                                                                                                     _GEN_2,
                                                                                                                     1'h0};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:30:19, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_12 =
    _signals_T_29 | _signals_T_31 | _signals_T_33 | _signals_T_35 | _signals_T_37
    | _signals_T_39 | _GEN_7;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_13 = _signals_T_7 | _signals_T_9;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [3:0]       signals_3 =
    _signals_T_1 | _signals_T_3 | _signals_T_5 | _GEN_13
      ? 4'h0
      : _signals_T_11
          ? 4'h1
          : _signals_T_13
              ? 4'h3
              : _signals_T_15
                  ? 4'h2
                  : _signals_T_17
                      ? 4'h4
                      : _signals_T_19 | _signals_T_21 | _signals_T_23 | _signals_T_25
                        | _signals_T_27 | _GEN_12
                          ? 4'h0
                          : _signals_T_45
                              ? 4'h5
                              : _signals_T_47 | _signals_T_49 | _signals_T_51
                                | _signals_T_53 | _signals_T_55 | _signals_T_57
                                | _signals_T_59 | _signals_T_61 | _signals_T_63
                                | _signals_T_65 | _signals_T_67 | _signals_T_69
                                  ? 4'h0
                                  : _signals_T_71
                                      ? 4'h6
                                      : _signals_T_73 ? 4'h7 : {_signals_T_75, 3'h0};	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_14 = _signals_T_47 | _signals_T_49 | _GEN_6;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [2:0]       signals_5 =
    _signals_T_1
      ? 3'h1
      : _signals_T_3
          ? 3'h3
          : _signals_T_5
              ? 3'h0
              : _GEN_13
                  ? 3'h1
                  : _GEN_11
                      ? 3'h2
                      : _GEN_9
                          ? 3'h0
                          : _signals_T_19
                              ? 3'h1
                              : _signals_T_21
                                  ? 3'h3
                                  : _GEN_10
                                      ? 3'h1
                                      : _signals_T_27
                                          ? 3'h0
                                          : _GEN_12
                                              ? 3'h1
                                              : _signals_T_45
                                                  ? 3'h0
                                                  : _GEN_14
                                                      ? 3'h1
                                                      : _GEN_5
                                                          ? 3'h0
                                                          : _GEN_4
                                                              ? 3'h1
                                                              : _GEN_3
                                                                  ? 3'h0
                                                                  : _signals_T_67
                                                                      ? 3'h1
                                                                      : _signals_T_69
                                                                          ? 3'h0
                                                                          : {1'h0,
                                                                             _GEN_2,
                                                                             1'h0};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:30:19, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [7:0][31:0] _GEN_15 =
    {{32'h0},
     {{{20{_imem_rdata[31]}},
       _imem_rdata[7],
       _imem_rdata[30:25],
       _imem_rdata[11:8],
       1'h0}},
     {{_imem_rdata[31:12], 12'h0}},
     {{{12{_imem_rdata[31]}},
       _imem_rdata[19:12],
       _imem_rdata[20],
       _imem_rdata[30:21],
       1'h0}},
     {{{20{_imem_rdata[31]}}, _imem_rdata[31:25], _imem_rdata[11:7]}},
     {{{20{_imem_rdata[31]}}, _imem_rdata[31:20]}},
     {32'h0},
     {32'h0}};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :30:19, :40:22, home/marigold/kanna/rv32i/npc/playground/src/utils/Function.scala:9:21, :10:{25,30,40}, :11:25, :12:{25,30,40}, :14:{25,35,44,58}, :15:25, :16:{35,49,59}, :17:25, :18:21, :20:{28,40}, :24:23, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [10:0]      _dmem_io_wmask_T =
    {3'h0,
     signals_3 == 4'h2 ? 8'hF : signals_3 == 4'h5 ? 8'h3 : {7'h0, signals_3 == 4'h4}}
    << _alu_io_alu_res[1:0];	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21, :126:27, :128:44, :133:33, src/main/scala/chisel3/util/Lookup.scala:34:39
  wire [62:0]      _dmem_io_wdata_T_1 =
    {31'h0, _regfile_io_rdata2} << {58'h0, _alu_io_alu_res[1:0], 3'h0};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25, :114:21, :126:27, :134:33, src/main/scala/chisel3/util/Lookup.scala:34:39
  wire [31:0]      rdata_shifted = _dmem_rdata >> {27'h0, _alu_io_alu_res[1:0], 3'h0};	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21, :121:22, :126:27, :137:35, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [31:0]      _next_pc_T = 32'(pc + 32'h4);	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, :153:28
  wire             branch =
    _GEN == 10'h67 | _imem_rdata[6:0] == 7'h6F
    | (_GEN == 10'hE3
         ? _regfile_io_rdata1 != _regfile_io_rdata2
         : _GEN == 10'h2E3
             ? $signed(_regfile_io_rdata1) >= $signed(_regfile_io_rdata2)
             : _GEN == 10'h63
                 ? _regfile_io_rdata1 == _regfile_io_rdata2
                 : _GEN == 10'h3E3
                     ? _regfile_io_rdata1 >= _regfile_io_rdata2
                     : _GEN == 10'h363
                         ? _regfile_io_rdata1 < _regfile_io_rdata2
                         : _GEN == 10'h263
                           & $signed(_regfile_io_rdata1) < $signed(_regfile_io_rdata2));	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :100:25, :164:19, :165:19, :166:{19,42}, :167:{19,49}, :168:{19,42}, :169:{19,42}, :170:{19,42}, :171:{19,49}, src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _branch_addr_T_1 = _GEN == 10'h67;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:176:19, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [31:0]      _branch_addr_T_3 = _alu_io_alu_res & 32'hFFFFFFFE;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21, :176:{41,44}
  wire [31:0]      _branch_addr_T_30 = 32'(pc + _GEN_15[signals_2]);	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, :177:36, home/marigold/kanna/rv32i/npc/playground/src/utils/Function.scala:24:23, src/main/scala/chisel3/util/Lookup.scala:34:39
  wire             _GEN_16 =
    _imem_rdata[6:0] == 7'h6F | _GEN == 10'hE3 | _GEN == 10'h2E3 | _GEN == 10'h63
    | _GEN == 10'h3E3 | _GEN == 10'h363 | _GEN == 10'h263;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :177:19, :178:19, :179:19, :180:19, :181:19, :182:19, :183:19, src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/chisel3/util/Mux.scala:126:16
  always @(posedge clock) begin	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7
    if (reset)	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7
      pc <= 32'h80000000;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21
    else if (branch) begin	// src/main/scala/chisel3/util/Mux.scala:126:16
      if (_branch_addr_T_1)	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:176:19
        pc <= _branch_addr_T_3;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, :176:41
      else if (_GEN_16)	// src/main/scala/chisel3/util/Mux.scala:126:16
        pc <= _branch_addr_T_30;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, :177:36
      else	// src/main/scala/chisel3/util/Mux.scala:126:16
        pc <= 32'h0;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, src/main/scala/chisel3/util/Mux.scala:126:16
    end
    else	// src/main/scala/chisel3/util/Mux.scala:126:16
      pc <= _next_pc_T;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, :153:28
  end // always @(posedge)
  MemDPIC imem (	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22
    .clk   (clock),
    .en    (1'h1),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:28:16
    .addr  (pc),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21
    .wmask (8'h0),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:30:19
    .wdata (32'h0),	// src/main/scala/chisel3/util/Mux.scala:126:16
    .rdata (_imem_rdata)
  );
  Regfiles regfile (	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25
    .clock     (clock),
    .io_raddr1 (_imem_rdata[19:15]),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :41:22
    .io_rdata1 (_regfile_io_rdata1),
    .io_raddr2 (_imem_rdata[24:20]),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :42:22
    .io_rdata2 (_regfile_io_rdata2),
    .io_waddr  (_imem_rdata[11:7]),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :40:22
    .io_wdata
      (signals_5 == 3'h2
         ? (signals_3 == 4'h8
              ? {{24{rdata_shifted[7]}}, rdata_shifted[7:0]}
              : signals_3 == 4'h7
                  ? {16'h0, rdata_shifted[15:0]}
                  : signals_3 == 4'h6
                      ? {{16{rdata_shifted[15]}}, rdata_shifted[15:0]}
                      : signals_3 == 4'h3
                          ? {24'h0, rdata_shifted[7:0]}
                          : signals_3 == 4'h1 ? _dmem_rdata : 32'h0)
         : signals_5 == 3'h3 ? _next_pc_T : signals_5 == 3'h1 ? _alu_io_alu_res : 32'h0),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21, :121:22, :137:35, :138:{22,27,45,65}, :139:{22,27,45,64}, :141:47, :150:46, :153:28, src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/chisel3/util/Mux.scala:126:16
    .io_wen
      ((_GEN_8
          ? 2'h1
          : _signals_T_5
              ? 2'h0
              : _signals_T_7 | _signals_T_9 | _GEN_11
                  ? 2'h1
                  : _GEN_9
                      ? 2'h0
                      : _signals_T_19 | _signals_T_21 | _GEN_10
                          ? 2'h1
                          : _signals_T_27
                              ? 2'h0
                              : _GEN_12
                                  ? 2'h1
                                  : _signals_T_45
                                      ? 2'h0
                                      : _GEN_14
                                          ? 2'h1
                                          : _GEN_5
                                              ? 2'h0
                                              : _GEN_4
                                                  ? 2'h1
                                                  : _GEN_3
                                                      ? 2'h0
                                                      : _signals_T_67
                                                          ? 2'h1
                                                          : _signals_T_69
                                                              ? 2'h0
                                                              : {1'h0, _GEN_2}) == 2'h1),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:30:19, :158:30, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
    .io_a0_val (_regfile_io_a0_val)
  );
  ALU alu (	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21
    .io_alu_op
      (_GEN_8
         ? 5'h1
         : _signals_T_5
             ? 5'h0
             : _signals_T_7 | _signals_T_9 | _signals_T_11 | _signals_T_13 | _signals_T_15
               | _signals_T_17 | _signals_T_19
                 ? 5'h1
                 : _signals_T_21
                     ? 5'h0
                     : _signals_T_23
                         ? 5'h2
                         : _signals_T_25
                             ? 5'h3
                             : _signals_T_27
                                 ? 5'h0
                                 : _signals_T_29 | _signals_T_31
                                     ? 5'h4
                                     : _signals_T_33
                                         ? 5'h2
                                         : _signals_T_35 | _signals_T_37
                                             ? 5'h5
                                             : _signals_T_39
                                                 ? 5'h6
                                                 : _GEN_7
                                                     ? 5'h7
                                                     : _signals_T_45
                                                         ? 5'h1
                                                         : _signals_T_47 | _signals_T_49
                                                             ? 5'h8
                                                             : _GEN_6
                                                                 ? 5'h9
                                                                 : _GEN_5
                                                                     ? 5'h0
                                                                     : _GEN_4
                                                                         ? 5'hA
                                                                         : _GEN_3
                                                                             ? 5'h0
                                                                             : _signals_T_67
                                                                                 ? 5'h3
                                                                                 : _signals_T_69
                                                                                     ? 5'h0
                                                                                     : {4'h0,
                                                                                        _GEN_2}),	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
    .io_alu_src1
      (signals_1 == 2'h1 ? _regfile_io_rdata1 : signals_1 == 2'h2 ? pc : 32'h0),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21, :100:25, :108:18, :109:18, src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/chisel3/util/Mux.scala:126:16
    .io_alu_src2 (signals_2 == 3'h1 ? _regfile_io_rdata2 : _GEN_15[signals_2]),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25, :112:{23,33}, home/marigold/kanna/rv32i/npc/playground/src/utils/Function.scala:24:23, src/main/scala/chisel3/util/Lookup.scala:34:39
    .io_alu_res  (_alu_io_alu_res)
  );
  MemDPIC dmem (	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:121:22
    .clk   (clock),
    .en    (|signals_3),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:123:29, src/main/scala/chisel3/util/Lookup.scala:34:39
    .addr  (_alu_io_alu_res),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:114:21
    .wmask (_dmem_io_wmask_T[7:0]),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:133:{19,33}
    .wdata (_dmem_io_wdata_T_1[31:0]),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:134:{19,33}
    .rdata (_dmem_rdata)
  );
  EbreakDPIC dpic_ebreak (	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:187:29
    .clk       (clock),
    .ebreak_en (_imem_rdata == 32'h100073),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22, :189:39, src/main/scala/chisel3/util/Lookup.scala:31:38
    .a0_val    (_regfile_io_a0_val)	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:100:25
  );
  ITraceDPIC itrace (	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:198:24
    .clk     (clock),
    .pc      (pc),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:23:21
    .inst    (_imem_rdata),	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:26:22
    .next_pc
      (branch
         ? (_branch_addr_T_1 ? _branch_addr_T_3 : _GEN_16 ? _branch_addr_T_30 : 32'h0)
         : _next_pc_T)	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:153:28, :176:{19,41}, :177:36, :192:17, :193:17, :195:17, src/main/scala/chisel3/util/Mux.scala:126:16
  );
  assign io_pc = pc;	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7, :23:21
  assign io_is_mmio =
    (|signals_3) & (~(_alu_io_alu_res[31]) | _alu_io_alu_res > 32'h87FFFFFF);	// home/marigold/kanna/rv32i/npc/playground/src/NPC_Top.scala:14:7, :114:21, :123:29, :204:{38,51,68,80}, src/main/scala/chisel3/util/Lookup.scala:34:39
endmodule



module EbreakDPIC (
    input wire clk,
    input wire ebreak_en,
    input [31:0] a0_val
);
    import "DPI-C" function void npc_ebreak(input int code);
    
    always @(posedge clk) begin
        if(ebreak_en)begin
            npc_ebreak(a0_val);
        end
    end
endmodule

module MemDPIC(
    input wire clk,
    input wire en,
    input wire [31:0] addr,
    input wire [7:0] wmask,
    input wire [31:0] wdata,
    output reg [31:0] rdata
);
    import "DPI-C" function int pmem_read(input int raddr);
    import "DPI-C" function void pmem_write(input int waddr, input int wdata, input byte wmask);

    always @(*) begin
        if (en) begin
            rdata = pmem_read(addr);
        end else begin
            rdata = 0;
        end
    end

    always @(posedge clk) begin
        if (en && wmask != 0) begin
            pmem_write(addr, wdata, wmask);
        end
    end

endmodule

module RegfileDPIC (
    input clk,
    input wen,
    input [4:0] waddr,
    input [31:0] wdata
);
    import "DPI-C" function void set_gpr_value(input int idx,input int value);

    always@(posedge clk)begin
        if(wen && waddr!=0)begin
            set_gpr_value({27'b0, waddr}, wdata);
        end
    end
    
endmodule

module ITraceDPIC (
    input clk,
    input [31:0] pc, 
    input [31:0] inst,
    input [31:0] next_pc
);
    import "DPI-C" function void npc_itrace(input int pc, input int next_pc,input int inst);

    always @(posedge clk) begin
        if (pc != 0) begin
            npc_itrace(pc, next_pc, inst);
        end
    end
    
endmodule

// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----

